# -*- coding: utf-8 -*-
# Copyright (C) 2023 Benjamin Thomas Schwertfeger
# GitHub: https://github.com/btschwertfeger
#

name: CI/CD

on:
  push:
    branches: [master]
  schedule:
    - cron: "20 16 */7 * *"
  release:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["**"]

concurrency:
  group: CICD
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  ## ===========================================================================
  ##    Checks the code logic, style and more
  ##
  Pre-Commit:
    uses: ./.github/workflows/_pre_commit.yaml

  ## ===========================================================================
  ##  Discover vulnerabilities
  ##
  # CodeQL:
  #   uses: ./.github/workflows/_codeql.yaml

  ## ===========================================================================
  ##    Builds the package on multiple OS
  ##
  Build:
    needs: [Pre-Commit]
    uses: ./.github/workflows/_build.yaml
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  ## ===========================================================================
  ##  Test the application
  ##  - FIXME: Can't be tested properly due to YouTube's bot detection mechanism
  ##
  # Test:
  #   # needs: [Pre-Commit]
  #   uses: ./.github/workflows/_test.yaml
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest]
  #       python-version: ["3.11"]
  #   with:
  #     python-version: ${{ matrix.python-version }}

  ## ===========================================================================
  ##    Upload the build artifacts
  ##
  Upload:
    if: |
      success() &&
      github.actor == 'btschwertfeger' &&
      github.event_name == 'release'
    needs: [Build] # Test
    uses: ./.github/workflows/_upload.yaml
